version: '3'
services:

  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: admin